### ISSUE TITLE
fact scaleio_mdm_clustersetup_needed wrong

### ISSUE THREAD

**Issue by Boran** [swisscom/puppet-scaleio#3]
On my system (EMC ScaleIO Version: R2_0.10000.2072)  "scli --query_cluster --approve_certificate"  gives a different output that "MDM cluster state is incorrect" when the cluster is not configured, so we need to add "MDM is not attached" as a match for this case i.e.

in lib/facter/scaleio_mdm_clustersetup_needed.rb 
'''
      output = Facter::Util::Resolution.exec('scli --query_cluster --approve_certificate 2>&1')
      output.nil? ? true : !!(output =~ /MDM is not attached|The MDM cluster state is incorrect/)
'''

likewise in mdm/cluster_setup.pp
```
onlyif  => 'scli --query_cluster --approve_certificate 2>&1 |grep -qE "MDM is not attached|Error: MDM failed command.  Status: The MDM cluster state is incorrect"',
```
however that should really just check the $scaleio_mdm_clustersetup_needed, not do the same check in a (possibly different) way??

**Comment by nordewal** [comment]
This is actually something that popped-up with ScaleIO 2.0.1. There is also other change for 2.0.1 that needed to be made in this puppet module. I fixed this internally already some time ago, but forgot to push the changes upstream - bad me...

Anyways I just pushed the version 3.1.1 that works with ScaleIO 2.0.1:
https://github.com/swisscom/puppet-scaleio/commit/cd09682f84ead9a461e59526bd6728753afa7e19

Thanks for bringing this to my attention. If this fixes your problem, please close this issue.

**Comment by Boran** [comment]
Hi, the patch make sense, good thanks. 

However a) one could shorten the matched strings to reduce the likelihood of a small word change in message causing a break and b)  the onliy if should not execute yet another duplicate command, but just check $scaleio_mdm_clustersetup_needed?

Also, is there no way in facter::util to check the return code, as opposed to output text of a command? That would be even cleaner.

**Comment by nordewal** [comment]
a) The point is, if we by mistaken end up with two ScaleIO clusters at a time, we will have data unavailability (DU). So we want to make sure to never create a new cluster by 'accidence'. With this we simply stick to the safe side.

b) You are right, this is something that could be slightly improved.

c) At least with earlier ScaleIO versions I encountered cases where I had the same return code with different text output. By checking the message we make sure that we're really in that state.

**Comment by Boran** [comment]
OK, thx.
